---
apiVersion: v1
kind: Namespace
metadata:
  name: maximo-cpi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpi
  namespace: maximo-cpi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcpi-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["list"]  
  - nonResourceURLs: ["*"]
    verbs: ["get"]
  #- apiGroups: [""]
  #  resources: ["pods/exec"]
  #  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcpi-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: mcpi
    namespace: maximo-cpi
roleRef:
  kind: ClusterRole
  name: mcpi-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcpi-ingress-exec-access
  namespace: openshift-ingress
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcpi-exec-access-binding
  namespace: openshift-ingress
subjects:
  - kind: ServiceAccount
    name: mcpi
    namespace: maximo-cpi
roleRef:
  kind: Role
  name: mcpi-ingress-exec-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpi-deployment
  namespace: maximo-cpi
  labels:
    app: mcpi
spec:
  replicas: 1
  imagePullPolicy: Always
  selector:
    matchLabels:
      app: mcpi
  template:
    metadata:
      labels:
        app: mcpi
    spec:
      #securityContext:
      #  runAsUser: 0  # no specify, the openshift uses the restricted by default
      serviceAccountName: mcpi
      #imagePullSecrets:
      #  - name: ibm-entitlement
      containers:
        - name: mcpi
          image: quay.io/brianzhu_ibm/mcpi:latest
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          env:
            - name: INCLUSTER
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mcpi-service
  namespace: maximo-cpi
spec:
  selector:
    app: mcpi
  ports:
    - name: viewer-port
      protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mcpi-viewer-route
  namespace: maximo-cpi
  labels: {}
spec:
  to:
    kind: Service
    name: mcpi-service
    weight: 100
  port:
    targetPort: viewer-port
  tls:
    termination: edge
  wildcardPolicy: None
